//Neel Madala
//9/1/2023
//This code is a game where the player guess a random number between 1 and 100 generated by the computer. The player is able to reset the game and end the game.
#include <iostream>

using namespace std;

int main()
{
  cout << "Welcome to Guessing Game! In this game enter random numbers between 1 and 100 " << endl << "until you guess the random number generated by the Computer." << endl; 
    //intialize variables
  int randnum = 0;
  char input;
  bool stillPlaying = true;
  int guess = 0;
  int tries = 0;
  while (stillPlaying == true) {
    //reset variables
    randnum = 0;
    guess = 0;
    tries = 0;
    // initialize random seed:
    srand (time(NULL));

    //generate a random number between 1 and 100
    randnum = rand() % 100 + 1;
    
    //Ask for input and check
    do {
      cout << endl <<"Guess the number (1 to 100)" << endl;
      cin >> guess;
      if (randnum>guess) {
	cout << endl << "The random number is higher than the guess" << endl;
      }
      if (randnum<guess) {
	cout << endl << "The random Number is Lower than the guess" << endl;
      }
      tries++;
    }while (randnum != guess);
    //ending message
    cout << endl <<"Congratulations! You guessed the random number in " << tries << " tries" << endl;
    cout << "Do you wish to play again (y/n)?" <<endl;
    cin >> input;
    //continue playing
    if (input == 'y') {
      stillPlaying = true;
    }
    //Stop playing
    if (input == 'n') {
      stillPlaying = false;
    }
  }
  cout << "Thanks for Playing" << endl;
}
